import { Dispute, DisputeStatus } from '../database/entities/dispute.entity';

export const seedDisputes: Partial<Dispute>[] = [
  {
    orderId: 'order-001',
    userId: 'user-001',
    sellerId: 'seller-001',
    status: 'OPEN' as DisputeStatus,
    reasonCode: 'DAMAGED_ITEM',
    description: 'Sản phẩm bị hư hỏng khi nhận hàng',
    createdBy: 'user-001',
    attachments: {
      images: ['image1.jpg', 'image2.jpg'],
    },
  },
  {
    orderId: 'order-002',
    userId: 'user-002',
    sellerId: 'seller-002',
    status: 'SELLER_RESPONDED' as DisputeStatus,
    reasonCode: 'WRONG_ITEM',
    description: 'Nhận sai sản phẩm so với đơn hàng',
    createdBy: 'user-002',
    updatedBy: 'seller-002',
  },
  {
    orderId: 'order-003',
    userId: 'user-003',
    sellerId: 'seller-001',
    status: 'ESCALATED' as DisputeStatus,
    reasonCode: 'NOT_RECEIVED',
    description: 'Chưa nhận được hàng sau 10 ngày',
    createdBy: 'user-003',
    escalatedAt: new Date(),
    updatedBy: 'user-003',
  },
  {
    orderId: 'order-004',
    userId: 'user-004',
    sellerId: 'seller-003',
    status: 'RESOLVED' as DisputeStatus,
    reasonCode: 'QUALITY_ISSUE',
    description: 'Chất lượng sản phẩm không đúng mô tả',
    resolution: 'Đã hoàn tiền 100% cho khách hàng',
    createdBy: 'user-004',
    resolvedAt: new Date(),
    updatedBy: 'admin-001',
  },
  {
    orderId: 'order-005',
    userId: 'user-005',
    sellerId: 'seller-002',
    status: 'REJECTED' as DisputeStatus,
    reasonCode: 'REFUND_REQUEST',
    description: 'Yêu cầu hoàn tiền',
    resolution: 'Yêu cầu không hợp lệ, sản phẩm đã được sử dụng',
    createdBy: 'user-005',
    resolvedAt: new Date(),
    updatedBy: 'admin-001',
  },
  {
    orderId: 'order-006',
    userId: 'user-001',
    sellerId: 'seller-004',
    status: 'OPEN' as DisputeStatus,
    reasonCode: 'LATE_DELIVERY',
    description: 'Giao hàng chậm hơn cam kết',
    createdBy: 'user-001',
  },
  {
    orderId: 'order-007',
    userId: 'user-006',
    sellerId: 'seller-005',
    status: 'SELLER_RESPONDED' as DisputeStatus,
    reasonCode: 'MISSING_ITEM',
    description: 'Thiếu một số sản phẩm trong đơn hàng',
    createdBy: 'user-006',
    updatedBy: 'seller-005',
  },
  {
    orderId: 'order-008',
    userId: 'user-007',
    sellerId: 'seller-001',
    status: 'ESCALATED' as DisputeStatus,
    reasonCode: 'FRAUD',
    description: 'Nghi ngờ gian lận từ phía người bán',
    createdBy: 'user-007',
    escalatedAt: new Date(),
    updatedBy: 'user-007',
  },
];

