topics:
  - name: order.created
    partitions: 6
    replication-factor: 1

  - name: payment.success
    partitions: 4
    replication-factor: 1

  - name: product.updated
    partitions: 3
    replication-factor: 1

  - name: user.created
    partitions: 3
    replication-factor: 1

  - name: payment.failed
    partitions: 2
    replication-factor: 1

  - name: product.created
    partitions: 3
    replication-factor: 1

  - name: product.low-stock
    partitions: 2
    replication-factor: 1

  - name: dispute.opened
    partitions: 2
    replication-factor: 1

  - name: dispute.escalated
    partitions: 2
    replication-factor: 1

  - name: dispute.resolved
    partitions: 2
    replication-factor: 1

  - name: settlement.balance.updated
    partitions: 3
    replication-factor: 1

  - name: settlement.payout.requested
    partitions: 3
    replication-factor: 1

  - name: dlq.failed-messages
    partitions: 2
    replication-factor: 1

  # Request-Reply Pattern A
  - name: inventory.reserve.request
    partitions: 2
    replication-factor: 1
  - name: inventory.reserve.reply
    partitions: 2
    replication-factor: 1
  - name: promotion.validate.request
    partitions: 2
    replication-factor: 1
  - name: promotion.validate.reply
    partitions: 2
    replication-factor: 1

  # Request-Reply Pattern B (aggregate)
  - name: order.prepare.request
    partitions: 2
    replication-factor: 1
  - name: order.prepare.reply
    partitions: 2
    replication-factor: 1

  # Analytics Streams output
  - name: analytics.revenue.daily
    partitions: 2
    replication-factor: 1
  - name: analytics.revenue.1m
    partitions: 2
    replication-factor: 1
  - name: analytics.revenue.5m
    partitions: 2
    replication-factor: 1
  - name: analytics.user.daily
    partitions: 2
    replication-factor: 1
  - name: analytics.product.daily
    partitions: 2
    replication-factor: 1
  - name: analytics.seller.daily
    partitions: 2
    replication-factor: 1
  - name: analytics.category.daily
    partitions: 2
    replication-factor: 1
